### ISSUE TITLE
Call for '../data/player-segment'

### ISSUE THREAD

**Issue by YilinGao-SHU** [sjtu-xai-lab/interaction-concept#1]
Thanks for you excellent work！When I try to reproduce your work, some error happened, like when I run 'python eval_interaction_image.py', there seen no such a file called '../data/player-segment'. So where does this file come from or how to create it? Looking forward to your reply :)

**Comment by xingzhongyu** [comment]
Same question

**Comment by dxl-Sense** [comment]
Thanks for your work in XAI. I want to reproduce yourt work, but I find your code have no dataset of player-segment. So could please upload this dataset or how to creata it? hope your reply.

**Comment by LeeQueue513** [comment]
Same question

**Comment by LMJJJJJJ** [comment]
Sorry for late reply. We have uploaded annotations for players at `data/player-segment`. Please check.
